/**
 * Shared design tokens for the Lynk-X web application.
 * 
 * This file is auto-generated from theme/tokens.json.
 * Do not edit this file manually.
 */
export const tokens = {
  "colors": {
    "brand": {
      "primary": "#20f928",
      "secondary": "#f9c920",
      "tertiary": "#322f35",
      "alternate": "#e0e3e7",
      "userLocation": "#FF0000"
    },
    "utility": {
      "primaryText": "#ffffff",
      "secondaryText": "#000000",
      "primaryBackground": "#000000",
      "secondaryBackground": "#ffffff"
    },
    "interface": {
      "success": "#0F8C16",
      "error": "#d32f2f",
      "surface": "#1E1E1E",
      "outline": "#E0E0E0"
    }
  },
  "spacing": {
    "xs": 4,
    "sm": 8,
    "md": 12,
    "lg": 16,
    "xl": 24,
    "xxl": 32,
    "huge": 48
  },
  "radius": {
    "xs": 2,
    "sm": 4,
    "md": 8,
    "lg": 12,
    "xl": 16,
    "xxl": 20,
    "full": 9999
  },
  "shadows": {
    "sm": {
      "color": "rgba(0, 0, 0, 0.1)",
      "offset": {
        "x": 0,
        "y": 1
      },
      "blur": 2,
      "spread": 0
    },
    "md": {
      "color": "rgba(0, 0, 0, 0.15)",
      "offset": {
        "x": 0,
        "y": 4
      },
      "blur": 6,
      "spread": -1
    },
    "lg": {
      "color": "rgba(0, 0, 0, 0.2)",
      "offset": {
        "x": 0,
        "y": 10
      },
      "blur": 15,
      "spread": -3
    }
  },
  "icons": {
    "xs": 16,
    "sm": 20,
    "md": 24,
    "lg": 32,
    "xl": 48
  },
  "typography": {
    "fontFamilies": {
      "primary": "Inter",
      "heading": "Inter Tight"
    },
    "styles": {
      "h1": {
        "family": "heading",
        "fontSize": 32,
        "fontWeight": 700,
        "letterSpacing": -0.5
      },
      "h2": {
        "family": "heading",
        "fontSize": 24,
        "fontWeight": 600,
        "letterSpacing": -0.4
      },
      "bodyLarge": {
        "family": "primary",
        "fontSize": 16,
        "fontWeight": 400
      },
      "bodyMedium": {
        "family": "primary",
        "fontSize": 14,
        "fontWeight": 400
      },
      "labelLarge": {
        "family": "primary",
        "fontSize": 14,
        "fontWeight": 500
      }
    }
  }
} as const;
